// Generates src/generated/git-sha.ts at BUILD TIME (prebuild/predev — see
// package.json; deliberately NOT postinstall, which also runs during the
// Docker build's `deps` stage, before GIT_SHA/.git exist there) — a file
// compiled into the app, not a runtime env var.
// Runtime-env would be circular for the one thing this exists to prove: an
// HTTP test that spawns its OWN server could set GIT_SHA itself and then
// assert its own value back, proving nothing about what was actually built.
//
// Resolution order:
//   1. process.env.GIT_SHA, if the builder provided one explicitly — the
//      Docker build context excludes .git (.dockerignore), so the image
//      build passes this via `--build-arg GIT_SHA=...`, forwarded from the
//      deploy script's own `git rev-parse HEAD` (it already computes this
//      value; this is a pass-through, not a second derivation).
//   2. `git rev-parse HEAD` directly — the normal case locally and in CI,
//      where .git is actually present.
//
// FAILS THE BUILD (non-zero exit) if neither resolves. Never writes a
// placeholder like "unknown": a provenance check that can "pass" on a
// placeholder is the same silent-degradation shape as everything else this
// project has been fixing today.
import { execSync } from 'node:child_process'
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dest = resolve(root, 'src/generated/git-sha.ts')

function resolveSha() {
  if (process.env.GIT_SHA) return process.env.GIT_SHA.trim()
  try {
    return execSync('git rev-parse HEAD', { cwd: root }).toString().trim()
  } catch {
    return null
  }
}

const sha = resolveSha()
if (!sha) {
  console.error(
    '[generate-git-sha] Could not determine the commit being built: GIT_SHA is ' +
      'unset and `git rev-parse HEAD` failed (no .git present — e.g. a Docker ' +
      'build context, which excludes it). Pass --build-arg GIT_SHA=<sha> instead ' +
      'of building without provenance.',
  )
  process.exit(1)
}

mkdirSync(dirname(dest), { recursive: true })
writeFileSync(
  dest,
  `// AUTO-GENERATED by scripts/generate-git-sha.mjs at build time — do not edit or commit.\nexport const GIT_SHA = ${JSON.stringify(sha)}\n`,
)
console.log(`[generate-git-sha] ${dest} <- ${sha}`)
